//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gardener.Base.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.Base.Resources.SharedLocalResource", typeof(SharedLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AccountName 的本地化字符串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AccountPassword 的本地化字符串。
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddChildren 的本地化字符串。
        /// </summary>
        public static string AddChildren {
            get {
                return ResourceManager.GetString("AddChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorizing 的本地化字符串。
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avatar 的本地化字符串。
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BatchDelete 的本地化字符串。
        /// </summary>
        public static string BatchDelete {
            get {
                return ResourceManager.GetString("BatchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BatchEdit 的本地化字符串。
        /// </summary>
        public static string BatchEdit {
            get {
                return ResourceManager.GetString("BatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BatchFakeDelete 的本地化字符串。
        /// </summary>
        public static string BatchFakeDelete {
            get {
                return ResourceManager.GetString("BatchFakeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin 的本地化字符串。
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding 的本地化字符串。
        /// </summary>
        public static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BindingApi 的本地化字符串。
        /// </summary>
        public static string BindingApi {
            get {
                return ResourceManager.GetString("BindingApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BindingResource 的本地化字符串。
        /// </summary>
        public static string BindingResource {
            get {
                return ResourceManager.GetString("BindingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break 的本地化字符串。
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CallBack 的本地化字符串。
        /// </summary>
        public static string CallBack {
            get {
                return ResourceManager.GetString("CallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CH 的本地化字符串。
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClickRefresh 的本地化字符串。
        /// </summary>
        public static string ClickRefresh {
            get {
                return ResourceManager.GetString("ClickRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client_Login_Fail 的本地化字符串。
        /// </summary>
        public static string Client_Login_Fail {
            get {
                return ResourceManager.GetString("Client_Login_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client_No_Find 的本地化字符串。
        /// </summary>
        public static string Client_No_Find {
            get {
                return ResourceManager.GetString("Client_No_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code_Gen_Template_Compile_Error 的本地化字符串。
        /// </summary>
        public static string Code_Gen_Template_Compile_Error {
            get {
                return ResourceManager.GetString("Code_Gen_Template_Compile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm_New_Password_Inconformity 的本地化字符串。
        /// </summary>
        public static string Confirm_New_Password_Inconformity {
            get {
                return ResourceManager.GetString("Confirm_New_Password_Inconformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting 的本地化字符串。
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection 的本地化字符串。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller_Need_Comment 的本地化字符串。
        /// </summary>
        public static string Controller_Need_Comment {
            get {
                return ResourceManager.GetString("Controller_Need_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateBy 的本地化字符串。
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatedTime 的本地化字符串。
        /// </summary>
        public static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateIdentityType 的本地化字符串。
        /// </summary>
        public static string CreateIdentityType {
            get {
                return ResourceManager.GetString("CreateIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron 的本地化字符串。
        /// </summary>
        public static string Cron {
            get {
                return ResourceManager.GetString("Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data_Key_Uniqueness_Conflict 的本地化字符串。
        /// </summary>
        public static string Data_Key_Uniqueness_Conflict {
            get {
                return ResourceManager.GetString("Data_Key_Uniqueness_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data_Not_Find 的本地化字符串。
        /// </summary>
        public static string Data_Not_Find {
            get {
                return ResourceManager.GetString("Data_Not_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataNotFound 的本地化字符串。
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteAndIncludChildren 的本地化字符串。
        /// </summary>
        public static string DeleteAndIncludChildren {
            get {
                return ResourceManager.GetString("DeleteAndIncludChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteSelected 的本地化字符串。
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop 的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do 的本地化字符串。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email_Server_No_Find 的本地化字符串。
        /// </summary>
        public static string Email_Server_No_Find {
            get {
                return ResourceManager.GetString("Email_Server_No_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EN 的本地化字符串。
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndTime 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception 的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail 的本地化字符串。
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FakeDelete 的本地化字符串。
        /// </summary>
        public static string FakeDelete {
            get {
                return ResourceManager.GetString("FakeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FatalException 的本地化字符串。
        /// </summary>
        public static string FatalException {
            get {
                return ResourceManager.GetString("FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field_Cannot_Be_Modified 的本地化字符串。
        /// </summary>
        public static string Field_Cannot_Be_Modified {
            get {
                return ResourceManager.GetString("Field_Cannot_Be_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field_In_Type_Not_Found 的本地化字符串。
        /// </summary>
        public static string Field_In_Type_Not_Found {
            get {
                return ResourceManager.GetString("Field_In_Type_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field_Required 的本地化字符串。
        /// </summary>
        public static string Field_Required {
            get {
                return ResourceManager.GetString("Field_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FieldChangeDetails 的本地化字符串。
        /// </summary>
        public static string FieldChangeDetails {
            get {
                return ResourceManager.GetString("FieldChangeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter_Group_Operate_Error 的本地化字符串。
        /// </summary>
        public static string Filter_Group_Operate_Error {
            get {
                return ResourceManager.GetString("Filter_Group_Operate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forbidden 的本地化字符串。
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GoHome 的本地化字符串。
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon 的本地化字符串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityId 的本地化字符串。
        /// </summary>
        public static string IdentityId {
            get {
                return ResourceManager.GetString("IdentityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityName 的本地化字符串。
        /// </summary>
        public static string IdentityName {
            get {
                return ResourceManager.GetString("IdentityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityNickName 的本地化字符串。
        /// </summary>
        public static string IdentityNickName {
            get {
                return ResourceManager.GetString("IdentityNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityType 的本地化字符串。
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid 的本地化字符串。
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ip 的本地化字符串。
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsContinue 的本地化字符串。
        /// </summary>
        public static string IsContinue {
            get {
                return ResourceManager.GetString("IsContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsDeleted 的本地化字符串。
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsLocked 的本地化字符串。
        /// </summary>
        public static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNullOrEmpty 的本地化字符串。
        /// </summary>
        public static string IsNullOrEmpty {
            get {
                return ResourceManager.GetString("IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastRunTime 的本地化字符串。
        /// </summary>
        public static string LastRunTime {
            get {
                return ResourceManager.GetString("LastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock 的本地化字符串。
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginClientType 的本地化字符串。
        /// </summary>
        public static string LoginClientType {
            get {
                return ResourceManager.GetString("LoginClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginId 的本地化字符串。
        /// </summary>
        public static string LoginId {
            get {
                return ResourceManager.GetString("LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginToken 的本地化字符串。
        /// </summary>
        public static string LoginToken {
            get {
                return ResourceManager.GetString("LoginToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxNumberOfErrors 的本地化字符串。
        /// </summary>
        public static string MaxNumberOfErrors {
            get {
                return ResourceManager.GetString("MaxNumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxNumberOfRuns 的本地化字符串。
        /// </summary>
        public static string MaxNumberOfRuns {
            get {
                return ResourceManager.GetString("MaxNumberOfRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile 的本地化字符串。
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextRunTime 的本地化字符串。
        /// </summary>
        public static string NextRunTime {
            get {
                return ResourceManager.GetString("NextRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NickName 的本地化字符串。
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No_Includ_File 的本地化字符串。
        /// </summary>
        public static string No_Includ_File {
            get {
                return ResourceManager.GetString("No_Includ_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No_Permission_Modify_The_Data 的本地化字符串。
        /// </summary>
        public static string No_Permission_Modify_The_Data {
            get {
                return ResourceManager.GetString("No_Permission_Modify_The_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoRowsAreSelected 的本地化字符串。
        /// </summary>
        public static string NoRowsAreSelected {
            get {
                return ResourceManager.GetString("NoRowsAreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberOfErrors 的本地化字符串。
        /// </summary>
        public static string NumberOfErrors {
            get {
                return ResourceManager.GetString("NumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberOfRuns 的本地化字符串。
        /// </summary>
        public static string NumberOfRuns {
            get {
                return ResourceManager.GetString("NumberOfRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumRetries 的本地化字符串。
        /// </summary>
        public static string NumRetries {
            get {
                return ResourceManager.GetString("NumRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnlineTime 的本地化字符串。
        /// </summary>
        public static string OnlineTime {
            get {
                return ResourceManager.GetString("OnlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate 的本地化字符串。
        /// </summary>
        public static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OperateConfirmMessage 的本地化字符串。
        /// </summary>
        public static string OperateConfirmMessage {
            get {
                return ResourceManager.GetString("OperateConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 的本地化字符串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page404Message 的本地化字符串。
        /// </summary>
        public static string Page404Message {
            get {
                return ResourceManager.GetString("Page404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent 的本地化字符串。
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password_Error 的本地化字符串。
        /// </summary>
        public static string Password_Error {
            get {
                return ResourceManager.GetString("Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PersonalSettings 的本地化字符串。
        /// </summary>
        public static string PersonalSettings {
            get {
                return ResourceManager.GetString("PersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PleaseSelect 的本地化字符串。
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PleaseSelectSearchField 的本地化字符串。
        /// </summary>
        public static string PleaseSelectSearchField {
            get {
                return ResourceManager.GetString("PleaseSelectSearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query_Value_Type_No_Find_Converter 的本地化字符串。
        /// </summary>
        public static string Query_Value_Type_No_Find_Converter {
            get {
                return ResourceManager.GetString("Query_Value_Type_No_Find_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshtoken_Cannot_Used_In_Authentication 的本地化字符串。
        /// </summary>
        public static string Refreshtoken_Cannot_Used_In_Authentication {
            get {
                return ResourceManager.GetString("Refreshtoken_Cannot_Used_In_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshtoken_No_Exist_Or_Expire 的本地化字符串。
        /// </summary>
        public static string Refreshtoken_No_Exist_Or_Expire {
            get {
                return ResourceManager.GetString("Refreshtoken_No_Exist_Or_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request_Url_Is_Invalid 的本地化字符串。
        /// </summary>
        public static string Request_Url_Is_Invalid {
            get {
                return ResourceManager.GetString("Request_Url_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResetOnlyOnce 的本地化字符串。
        /// </summary>
        public static string ResetOnlyOnce {
            get {
                return ResourceManager.GetString("ResetOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource 的本地化字符串。
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource_Key_Repeat 的本地化字符串。
        /// </summary>
        public static string Resource_Key_Repeat {
            get {
                return ResourceManager.GetString("Resource_Key_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResourceId 的本地化字符串。
        /// </summary>
        public static string ResourceId {
            get {
                return ResourceManager.GetString("ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResuqesException 的本地化字符串。
        /// </summary>
        public static string ResuqesException {
            get {
                return ResourceManager.GetString("ResuqesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResuqesFail 的本地化字符串。
        /// </summary>
        public static string ResuqesFail {
            get {
                return ResourceManager.GetString("ResuqesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RetryTimeout 的本地化字符串。
        /// </summary>
        public static string RetryTimeout {
            get {
                return ResourceManager.GetString("RetryTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunOnceOnStart 的本地化字符串。
        /// </summary>
        public static string RunOnceOnStart {
            get {
                return ResourceManager.GetString("RunOnceOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduler_Not_Find 的本地化字符串。
        /// </summary>
        public static string Scheduler_Not_Find {
            get {
                return ResourceManager.GetString("Scheduler_Not_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduling 的本地化字符串。
        /// </summary>
        public static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script_Code_Compile_Fail 的本地化字符串。
        /// </summary>
        public static string Script_Code_Compile_Fail {
            get {
                return ResourceManager.GetString("Script_Code_Compile_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script_Code_JobDetail_Not_Find 的本地化字符串。
        /// </summary>
        public static string Script_Code_JobDetail_Not_Find {
            get {
                return ResourceManager.GetString("Script_Code_JobDetail_Not_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script_Code_JobId_Inconsistency 的本地化字符串。
        /// </summary>
        public static string Script_Code_JobId_Inconsistency {
            get {
                return ResourceManager.GetString("Script_Code_JobId_Inconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search_Error_DB_Field_Is_Null 的本地化字符串。
        /// </summary>
        public static string Search_Error_DB_Field_Is_Null {
            get {
                return ResourceManager.GetString("Search_Error_DB_Field_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SeedData 的本地化字符串。
        /// </summary>
        public static string SeedData {
            get {
                return ResourceManager.GetString("SeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectAll 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SendImage 的本地化字符串。
        /// </summary>
        public static string SendImage {
            get {
                return ResourceManager.GetString("SendImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service 的本地化字符串。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SessionDisableSendMessage 的本地化字符串。
        /// </summary>
        public static string SessionDisableSendMessage {
            get {
                return ResourceManager.GetString("SessionDisableSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SettingRoles 的本地化字符串。
        /// </summary>
        public static string SettingRoles {
            get {
                return ResourceManager.GetString("SettingRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartNow 的本地化字符串。
        /// </summary>
        public static string StartNow {
            get {
                return ResourceManager.GetString("StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartTime 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeed 的本地化字符串。
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sugar_Repository_Init_Fail 的本地化字符串。
        /// </summary>
        public static string Sugar_Repository_Init_Fail {
            get {
                return ResourceManager.GetString("Sugar_Repository_Init_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System_Default_Error_Message 的本地化字符串。
        /// </summary>
        public static string System_Default_Error_Message {
            get {
                return ResourceManager.GetString("System_Default_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemNotification 的本地化字符串。
        /// </summary>
        public static string SystemNotification {
            get {
                return ResourceManager.GetString("SystemNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemTenant 的本地化字符串。
        /// </summary>
        public static string SystemTenant {
            get {
                return ResourceManager.GetString("SystemTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemTenantResource 的本地化字符串。
        /// </summary>
        public static string SystemTenantResource {
            get {
                return ResourceManager.GetString("SystemTenantResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table_Name_Exist 的本地化字符串。
        /// </summary>
        public static string Table_Name_Exist {
            get {
                return ResourceManager.GetString("Table_Name_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task_Allready_Exist 的本地化字符串。
        /// </summary>
        public static string Task_Allready_Exist {
            get {
                return ResourceManager.GetString("Task_Allready_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task_Not_Exist 的本地化字符串。
        /// </summary>
        public static string Task_Not_Exist {
            get {
                return ResourceManager.GetString("Task_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tel 的本地化字符串。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tenant 的本地化字符串。
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TenantId 的本地化字符串。
        /// </summary>
        public static string TenantId {
            get {
                return ResourceManager.GetString("TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Times 的本地化字符串。
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timespan_Is_Expired 的本地化字符串。
        /// </summary>
        public static string Timespan_Is_Expired {
            get {
                return ResourceManager.GetString("Timespan_Is_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token_Invalid 的本地化字符串。
        /// </summary>
        public static string Token_Invalid {
            get {
                return ResourceManager.GetString("Token_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unauthorized 的本地化字符串。
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock 的本地化字符串。
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateBy 的本地化字符串。
        /// </summary>
        public static string UpdateBy {
            get {
                return ResourceManager.GetString("UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdatedTime 的本地化字符串。
        /// </summary>
        public static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateIdentityType 的本地化字符串。
        /// </summary>
        public static string UpdateIdentityType {
            get {
                return ResourceManager.GetString("UpdateIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UplaodAvatar 的本地化字符串。
        /// </summary>
        public static string UplaodAvatar {
            get {
                return ResourceManager.GetString("UplaodAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UploadFail 的本地化字符串。
        /// </summary>
        public static string UploadFail {
            get {
                return ResourceManager.GetString("UploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User_Info_Get_Error_Retry_Login 的本地化字符串。
        /// </summary>
        public static string User_Info_Get_Error_Retry_Login {
            get {
                return ResourceManager.GetString("User_Info_Get_Error_Retry_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User_Locked 的本地化字符串。
        /// </summary>
        public static string User_Locked {
            get {
                return ResourceManager.GetString("User_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User_Name_Or_Password_Error 的本地化字符串。
        /// </summary>
        public static string User_Name_Or_Password_Error {
            get {
                return ResourceManager.GetString("User_Name_Or_Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User_Name_Repeat 的本地化字符串。
        /// </summary>
        public static string User_Name_Repeat {
            get {
                return ResourceManager.GetString("User_Name_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserAgent 的本地化字符串。
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserCenter 的本地化字符串。
        /// </summary>
        public static string UserCenter {
            get {
                return ResourceManager.GetString("UserCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify_Code_Verification_Failed 的本地化字符串。
        /// </summary>
        public static string Verify_Code_Verification_Failed {
            get {
                return ResourceManager.GetString("Verify_Code_Verification_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn 的本地化字符串。
        /// </summary>
        public static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
