//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gardener.Email.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.Email.Resources.EmailLocalResource", typeof(EmailLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AccountName 的本地化字符串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AccountPassword 的本地化字符串。
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmailServerConfig 的本地化字符串。
        /// </summary>
        public static string ContentTemplate {
            get {
                return ResourceManager.GetString("ContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmailServerConfig 的本地化字符串。
        /// </summary>
        public static string EmailServerConfig {
            get {
                return ResourceManager.GetString("EmailServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmailServerConfigId 的本地化字符串。
        /// </summary>
        public static string EmailServerConfigId {
            get {
                return ResourceManager.GetString("EmailServerConfigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmailTemplate 的本地化字符串。
        /// </summary>
        public static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnableSsl 的本地化字符串。
        /// </summary>
        public static string EnableSsl {
            get {
                return ResourceManager.GetString("EnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example 的本地化字符串。
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FromEmail 的本地化字符串。
        /// </summary>
        public static string FromEmail {
            get {
                return ResourceManager.GetString("FromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FromName 的本地化字符串。
        /// </summary>
        public static string FromName {
            get {
                return ResourceManager.GetString("FromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsHtml 的本地化字符串。
        /// </summary>
        public static string IsHtml {
            get {
                return ResourceManager.GetString("IsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SendEmailInput 的本地化字符串。
        /// </summary>
        public static string SendEmailInput {
            get {
                return ResourceManager.GetString("SendEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServerTag 的本地化字符串。
        /// </summary>
        public static string ServerTag {
            get {
                return ResourceManager.GetString("ServerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubjectTemplate 的本地化字符串。
        /// </summary>
        public static string SubjectTemplate {
            get {
                return ResourceManager.GetString("SubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateId 的本地化字符串。
        /// </summary>
        public static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToEmail 的本地化字符串。
        /// </summary>
        public static string ToEmail {
            get {
                return ResourceManager.GetString("ToEmail", resourceCulture);
            }
        }
    }
}
