//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gardener.EasyJob.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EasyJobLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EasyJobLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.EasyJob.Resources.EasyJobLocalResource", typeof(EasyJobLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Archived 的本地化字符串。
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AssemblyName 的本地化字符串。
        /// </summary>
        public static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backlog 的本地化字符串。
        /// </summary>
        public static string Backlog {
            get {
                return ResourceManager.GetString("Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaseInfo 的本地化字符串。
        /// </summary>
        public static string BaseInfo {
            get {
                return ResourceManager.GetString("BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BasicInformation 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blocked 的本地化字符串。
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BuiltIn 的本地化字符串。
        /// </summary>
        public static string BuiltIn {
            get {
                return ResourceManager.GetString("BuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClusterId 的本地化字符串。
        /// </summary>
        public static string ClusterId {
            get {
                return ResourceManager.GetString("ClusterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concurrent 的本地化字符串。
        /// </summary>
        public static string Concurrent {
            get {
                return ResourceManager.GetString("Concurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron 的本地化字符串。
        /// </summary>
        public static string Cron {
            get {
                return ResourceManager.GetString("Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElapsedTime 的本地化字符串。
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnableRealTimeMonitor 的本地化字符串。
        /// </summary>
        public static string EnableRealTimeMonitor {
            get {
                return ResourceManager.GetString("EnableRealTimeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndTime 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ErrorToReady 的本地化字符串。
        /// </summary>
        public static string ErrorToReady {
            get {
                return ResourceManager.GetString("ErrorToReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception 的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExceptionMessage 的本地化字符串。
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GroupName 的本地化字符串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Http 的本地化字符串。
        /// </summary>
        public static string Http {
            get {
                return ResourceManager.GetString("Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityId 的本地化字符串。
        /// </summary>
        public static string IdentityId {
            get {
                return ResourceManager.GetString("IdentityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityType 的本地化字符串。
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IncludeAnnotations 的本地化字符串。
        /// </summary>
        public static string IncludeAnnotations {
            get {
                return ResourceManager.GetString("IncludeAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval 的本地化字符串。
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job 的本地化字符串。
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobDetailDescription 的本地化字符串。
        /// </summary>
        public static string JobDetailDescription {
            get {
                return ResourceManager.GetString("JobDetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobId 的本地化字符串。
        /// </summary>
        public static string JobId {
            get {
                return ResourceManager.GetString("JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobName 的本地化字符串。
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobTriggerDescription 的本地化字符串。
        /// </summary>
        public static string JobTriggerDescription {
            get {
                return ResourceManager.GetString("JobTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobTriggers 的本地化字符串。
        /// </summary>
        public static string JobTriggers {
            get {
                return ResourceManager.GetString("JobTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobType 的本地化字符串。
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JobTypeFullName 的本地化字符串。
        /// </summary>
        public static string JobTypeFullName {
            get {
                return ResourceManager.GetString("JobTypeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastRunTime 的本地化字符串。
        /// </summary>
        public static string LastRunTime {
            get {
                return ResourceManager.GetString("LastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxNumberOfErrors 的本地化字符串。
        /// </summary>
        public static string MaxNumberOfErrors {
            get {
                return ResourceManager.GetString("MaxNumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxNumberOfRuns 的本地化字符串。
        /// </summary>
        public static string MaxNumberOfRuns {
            get {
                return ResourceManager.GetString("MaxNumberOfRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextRunTime 的本地化字符串。
        /// </summary>
        public static string NextRunTime {
            get {
                return ResourceManager.GetString("NextRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotStart 的本地化字符串。
        /// </summary>
        public static string NotStart {
            get {
                return ResourceManager.GetString("NotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberOfErrors 的本地化字符串。
        /// </summary>
        public static string NumberOfErrors {
            get {
                return ResourceManager.GetString("NumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberOfRuns 的本地化字符串。
        /// </summary>
        public static string NumberOfRuns {
            get {
                return ResourceManager.GetString("NumberOfRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumRetries 的本地化字符串。
        /// </summary>
        public static string NumRetries {
            get {
                return ResourceManager.GetString("NumRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overrun 的本地化字符串。
        /// </summary>
        public static string Overrun {
            get {
                return ResourceManager.GetString("Overrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Panic 的本地化字符串。
        /// </summary>
        public static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RealTimeMonitor 的本地化字符串。
        /// </summary>
        public static string RealTimeMonitor {
            get {
                return ResourceManager.GetString("RealTimeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResetOnlyOnce 的本地化字符串。
        /// </summary>
        public static string ResetOnlyOnce {
            get {
                return ResourceManager.GetString("ResetOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResetOnlyOnceTIPS 的本地化字符串。
        /// </summary>
        public static string ResetOnlyOnceTIPS {
            get {
                return ResourceManager.GetString("ResetOnlyOnceTIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RetryTimeout 的本地化字符串。
        /// </summary>
        public static string RetryTimeout {
            get {
                return ResourceManager.GetString("RetryTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunningStatus 的本地化字符串。
        /// </summary>
        public static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunOnceOnStart 的本地化字符串。
        /// </summary>
        public static string RunOnceOnStart {
            get {
                return ResourceManager.GetString("RunOnceOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScriptCode 的本地化字符串。
        /// </summary>
        public static string ScriptCode {
            get {
                return ResourceManager.GetString("ScriptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartNow 的本地化字符串。
        /// </summary>
        public static string StartNow {
            get {
                return ResourceManager.GetString("StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartTime 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded 的本地化字符串。
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysJobCluster 的本地化字符串。
        /// </summary>
        public static string SysJobCluster {
            get {
                return ResourceManager.GetString("SysJobCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysJobDetail 的本地化字符串。
        /// </summary>
        public static string SysJobDetail {
            get {
                return ResourceManager.GetString("SysJobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysJobLog 的本地化字符串。
        /// </summary>
        public static string SysJobLog {
            get {
                return ResourceManager.GetString("SysJobLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysJobLogElapsedTime 的本地化字符串。
        /// </summary>
        public static string SysJobLogElapsedTime {
            get {
                return ResourceManager.GetString("SysJobLogElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysJobTrigger 的本地化字符串。
        /// </summary>
        public static string SysJobTrigger {
            get {
                return ResourceManager.GetString("SysJobTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysJobUserConfig 的本地化字符串。
        /// </summary>
        public static string SysJobUserConfig {
            get {
                return ResourceManager.GetString("SysJobUserConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TaskSittings 的本地化字符串。
        /// </summary>
        public static string TaskSittings {
            get {
                return ResourceManager.GetString("TaskSittings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerArgs 的本地化字符串。
        /// </summary>
        public static string TriggerArgs {
            get {
                return ResourceManager.GetString("TriggerArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerAssemblyType 的本地化字符串。
        /// </summary>
        public static string TriggerAssemblyType {
            get {
                return ResourceManager.GetString("TriggerAssemblyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerId 的本地化字符串。
        /// </summary>
        public static string TriggerId {
            get {
                return ResourceManager.GetString("TriggerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerStatus 的本地化字符串。
        /// </summary>
        public static string TriggerStatus {
            get {
                return ResourceManager.GetString("TriggerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnknownJobAssembly 的本地化字符串。
        /// </summary>
        public static string UnknownJobAssembly {
            get {
                return ResourceManager.GetString("UnknownJobAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnknownTriggerType 的本地化字符串。
        /// </summary>
        public static string UnknownTriggerType {
            get {
                return ResourceManager.GetString("UnknownTriggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unoccupied 的本地化字符串。
        /// </summary>
        public static string Unoccupied {
            get {
                return ResourceManager.GetString("Unoccupied", resourceCulture);
            }
        }
    }
}
